name: Node.js CI/CD Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */6 * * *"  # Run every 6 hours automatically

jobs:
  run-bot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update asitha2.json with current timestamp
      id: update_time
      run: |
        CURRENT_TIME=$(date +%s%3N)
        echo "{\"lastActive\": \"$CURRENT_TIME\"}" > asitha2.json

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install   # <-- FIXED HERE (was npm ci)

      - name: Start bot (6-hour session)
        run: |
          echo "🚀 Starting WhatsApp bot..."
          nohup node start.js &
          sleep 21500  # ~6 hours runtime
          echo "🕒 6 hours completed — restarting..."

      - name: Trigger self-restart via GitHub API
        if: always()
        run: |
          echo "🔁 Triggering workflow restart..."
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.PERSONAL_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/main.yml/dispatches \
            -d '{"ref":"main"}'
